[package]
name = "tect_control"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.17",features = ["serialize"]}
tect_state = { path = "../tect_state", version = "0.1.0", default-features = false }
tect_assetload = { path = "../tect_assetload", version = "0.1.0", default-features = false }
serde = "1"

[lints]
workspace = true
